# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9adbe418857ce3a9959e1f86a4440afd05d50f546f3d9f764a01230ace7b34cb0d91086448b402d918e43ed0663311c9e4c530dcb99ab4b7e77d6bb2fef91020

test:
  secret_key_base: 4bbb5c79534957aac5decfe02ebcf07b9612572d24cd4ed6397bd96743175c469e19c3651328c81549f97130feb70d4a352d43ceefbf949d1b165865ad8b88e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
